[package]
name = "offscreen_gl_context"
license = "MIT / Apache-2.0"
edition = "2018"
version = "0.23.0"
authors = ["Emilio Cobos Álvarez <emilio@crisal.io>", "The Servo Project Developers"]
description = "Creation and manipulation of HW accelerated offscreen rendering contexts in multiple platforms. Originally intended for the Servo project's WebGL implementation."
repository = "https://github.com/servo/rust-offscreen-rendering-context"
build = "build.rs"

[build-dependencies]
gl_generator = "0.11"

[features]
default = ["x11"]
osmesa = ["osmesa-sys"]
no_wgl = []
# NOTE: Just for testing use, there are no other changes
test_egl_in_linux = ["libloading", "lazy_static"]

[dependencies]
euclid = "0.20"
gleam = "0.6"
lazy_static = { version = "1", optional = true }
libloading = { version = "0.5", optional = true, default-features = false }
log = "0.4"
osmesa-sys = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[target.x86_64-apple-darwin.dependencies]
core-foundation = "0.6"
cgl = "0.2.3"
io-surface = "0.12.0"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"
libloading = { version = "0.5", default-features = false }

[target.'cfg(all(unix, not(any(target_os = "macos", target_os = "android", target_os = "ios"))))'.dependencies.x11]
optional = true
version = "2.3.0"
features = ["xlib"]

# Ensure that we have a static libEGL.lib present for linking with EGL bindings.
[target.'cfg(target_os = "windows")'.dev-dependencies]
mozangle = { version = "0.2", features = ["egl"] }

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["wingdi", "winuser", "libloaderapi"] }

[target.'cfg(any(target_os="macos", target_os="windows", target_os="android", target_os="ios"))'.dependencies]
lazy_static = "1"

[target.'cfg(any(target_os = "android", target_os = "windows"))'.dependencies]
libloading = { version = "0.5", default-features = false }
